### ISSUE TITLE
javacpp-port: Use reference instead of pointers to array in method arguments

### ISSUE THREAD

**Issue by andreasdr** [andreasdr/tdme2#1]
To be able to port the engine quickly from JAVA to C++, we decided for several reasons to pass std::array and std::vector with pointers instead of references when calling methods.

In a C++ manner you would rather pass with references.

So if interessted look in src/**/* for std::arrays, std::vectors beeing passed as pointers instead of references in methods and change it to references. If also appliable you could apply some constness.

**Comment by mahula** [comment]
This issue has been reopened. Is there anything left to do?

**Comment by andreasdr** [comment]
Hi, 

a quick grep spits out some results:

But only those should be improved:
```
src/tdme/engine/fileio/models/DAEReader.h:139:	static void readGeometry(const string& pathName, Model* model, Group* group, TiXmlElement* xmlRoot, const string& xmlNodeId, const map<string, string>* materialSymbols); // TODO: std container: maybe use call by reference
src/tdme/engine/fileio/models/WFObjReader.h:52:	static void readMaterials(const string& pathName, const string& fileName, map<string, Material*>* materials); // TODO: std container: maybe use call by reference
src/tdme/engine/fileio/models/DAEReader.cpp:690:void DAEReader::readGeometry(const string& pathName, Model* model, Group* group, TiXmlElement* xmlRoot, const string& xmlNodeId, const map<string, string>* materialSymbols)
src/tdme/engine/fileio/models/WFObjReader.cpp:339:void WFObjReader::readMaterials(const string& pathName, const string& fileName, map<string, Material*>* materials)
```

There is a comment here, that can be removed.
`src/tdme/engine/subsystems/rendering/Object3DGroupMesh.h:89:	static Object3DGroupMesh* createMesh(Object3DGroupRenderer* object3DGroupRenderer, Engine::AnimationProcessingTarget animationProcessingTarget, Group* group, map<string, Matrix4x4*>& transformationMatrices, map<string, Matrix4x4*>* skinningMatrices); // TODO: std container: maybe use call by reference`

**Comment by andreasdr** [comment]
I am closing this issue now. Most occurrences has been fixed from @mahula 
At some cases it might also make sense.
