### ISSUE TITLE
Please don't drop support for MSYS2 MINGW64

### ISSUE THREAD

**Issue by ghost** [andreasdr/tdme2#21]
Your project is building fine on MSYS2 MINGW64 on Windows 8.1 64 bit. Don't be a MSVC-only project!

**Comment by andreasdr** [comment]
Hi, We dont drop support for MSYS2 MINGW64. However we have problems with ReactPhysics3D 0.7 and current MSYS2 MINGW64.

We are in progress to update to ReactPhysics 0.9 which solve that problems. The update lives in rp3d-0.9 branch. However we need to fix some bugs there still.
