### ISSUE TITLE
CLion/CMake

### ISSUE THREAD

**Issue by RUSshy** [andreasdr/tdme2#5]
Hi

I would like to use the ide clion but it only support cmake, is it possible to support cmake ?

Thanks

**Comment by andreasdr** [comment]
Hi,

if you are a bit familiar with CMake it should not be a big problem.
Its just a question of providing the right include paths and the static libraries.

You can have a look at the current makefiles to get this information.

I will set up a sample project if I find some time.

Many thanx and

Best regards
Andreas

**Comment by RUSshy** [comment]
Thanks for your reply

I'm still a beginner, but i'll try again to create the cmake script, the main problem i had was the dependencies

**Comment by andreasdr** [comment]
Hi,

I can help a bit maybe. Which OS are you using?

BTW: I do not thing that TDME2 is yet very beginner friendly. But this might depend on what you like to do with it.

Best regards
Andreas
